# Generated by Django 4.2 on 2024-04-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("desevapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="cursos",
            field=models.ManyToManyField(
                blank=True, to="desevapp.curso", verbose_name="cursos"
            ),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="cursos",
            field=models.ManyToManyField(to="desevapp.curso", verbose_name="cursos"),
        ),
    ]
